<?php
// $Id$

/**
 * Uses system_settings_form
 */
function js_redirect_admin() {
	$form = array();

	$default = <<<EOD
[
	{ "noscript": "/example-url", "enhanced": "/example-url-enhanced" },
	{ "noscript": "/another-example-url", "enhanced": "/another-example-url-enhanced", "type": "is equal" }	
]
EOD;

	$form['js_redirect_mapping'] = array(
		'#type' => 'textarea',
		'#title' => t('Normal page and enhanced page'),
		'#cols' => 90,
		'#rows' => 25,
		'#default_value' => variable_get('js_redirect_mapping', $default),
		'#description' => t('Put all your link mappings in here in the form %default (JSON). Possible values for "type" are: "is equal", "not equal", "starts with", "ends with" and "contains".', array(
			'%default' => $default
		)),
	);

	$form['js_redirect_mapping']['#suffix'] = '<h2>' . t('Active redirects') . '</h2>';
	if(js_redirect_get_mapping() !== null) {
		$form['js_redirect_mapping']['#suffix'] .= '<ul>';
		foreach(js_redirect_get_mapping() as $l) {
			if($l['noscript'][0] == '/') {
			
			}
			$form['js_redirect_mapping']['#suffix'] .= sprintf('<li>%s -> %s</li>', l($l['noscript'], ltrim($l['noscript'], '/')), l($l['enhanced'], ltrim($l['enhanced'], '/')));
		}
		$form['js_redirect_mapping']['#suffix'] .= '</ul>';
	} else {
		$form['js_redirect_mapping']['#suffix'] .= '<p>' . t('None') . '</p>';
	}

	return system_settings_form($form);
}

/**
 * Implements hook_menu()
 */
function js_redirect_menu() {
	$items = array();

	$items['admin/settings/js-redirect'] = array(
		'title' => 'JS Redirect',
		'description' => 'Edit JS Redirect Settings',
		'page callback' => 'drupal_get_form',
		'page arguments' => array('js_redirect_admin'),
		'access arguments' => array('access administration pages'),
		'type' => MENU_NORMAL_ITEM,
	 );

	return $items;
}

/**
 * @return array
 */
function js_redirect_get_mapping() {
	return json_decode(variable_get('js_redirect_mapping', ''), TRUE);
}

/**
 * Implements hook_preprocess_page()
 */
function js_redirect_preprocess_page(&$vars) {
	drupal_add_js(
		array(
			'js_redirect' => array(
				'mapping' => js_redirect_get_mapping()
			)
		), 'setting');
	drupal_add_js(drupal_get_path('module', 'js_redirect') . '/js/redirect.js', 'module');
	$vars['scripts'] = drupal_get_js();
}
